<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.OpenIdConnect" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.TestHost" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" />
    <PackageVersion Include="Microsoft.OpenApi" Version="2.7.5" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.61.0" />
    <PackageVersion Include="Npgsql" Version="10.0.3" />
    <PackageVersion Include="OpenIddict.EntityFrameworkCore" Version="7.6.0" />
    <PackageVersion Include="OpenIddict.Server.AspNetCore" Version="7.6.0" />
    <PackageVersion Include="OpenIddict.Validation.AspNetCore" Version="7.6.0" />
    <PackageVersion Include="OpenIddict.Validation.ServerIntegration" Version="7.6.0" />
    <PackageVersion Include="SQLitePCLRaw.lib.e_sqlite3" Version="2.1.12" />
    <PackageVersion Include="Skopka.Abstraction.OperationResult" Version="0.2.0" />
    <PackageVersion Include="Skopka.Identity" Version="0.10.0" />
    <PackageVersion Include="Skopka.Identity.Abstractions" Version="0.10.0" />
    <PackageVersion Include="Skopka.Identity.Ef.PostgreSql" Version="0.10.0" />
    <PackageVersion Include="Skopka.Identity.Infrastructure" Version="0.10.0" />
    <PackageVersion Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.2.3" />
    <PackageVersion Include="Testcontainers.PostgreSql" Version="4.13.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>
