<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Skopka.Identity" />
    <PackageReference Include="Skopka.Identity.Abstractions" />
    <PackageReference Include="Skopka.Identity.Ef.PostgreSql" />
    <PackageReference Include="Skopka.Identity.Infrastructure" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\..\src\Skopka.Hello\Skopka.Hello.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Hello.Endpoints\Skopka.Hello.Endpoints.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Hello.UI\Skopka.Hello.UI.csproj" />
  </ItemGroup>
</Project>
