<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" />
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
    <PackageReference Include="SSH.NET" />
    <PackageReference Include="Skopka.Identity" />
    <PackageReference Include="Skopka.Identity.Abstractions" />
    <PackageReference Include="Skopka.Identity.Ef.PostgreSql" />
    <PackageReference Include="Skopka.Identity.Infrastructure" />
    <PackageReference Include="Testcontainers.PostgreSql" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <ProjectReference Include="..\..\src\Skopka.Hello\Skopka.Hello.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Hello.Admin\Skopka.Hello.Admin.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Hello.AuthorizationServer\Skopka.Hello.AuthorizationServer.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Hello.Endpoints\Skopka.Hello.Endpoints.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Hello.Oidc\Skopka.Hello.Oidc.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Hello.Server\Skopka.Hello.Server.csproj" />
    <ProjectReference Include="..\..\src\Skopka.Hello.UI\Skopka.Hello.UI.csproj" />
  </ItemGroup>
</Project>
