<Project Sdk="Microsoft.NET.Sdk.Razor">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
    <Description>Administration API and UI boundary for Skopka.Hello.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\Skopka.Hello\Skopka.Hello.csproj" />
    <ProjectReference Include="..\Skopka.Hello.Endpoints\Skopka.Hello.Endpoints.csproj" />
    <ProjectReference Include="..\Skopka.Hello.UI\Skopka.Hello.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Localization\Resources\*.json"
                      LogicalName="Skopka.Hello.Admin.Localization.%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
