<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Description>OAuth 2.0 and OpenID Connect authorization server adapter for Skopka.Hello.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="OpenIddict.Server.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.ServerIntegration" />
    <ProjectReference Include="..\Skopka.Hello\Skopka.Hello.csproj" />
  </ItemGroup>
</Project>
